### Register
POST localhost:8080/api/user/register
Content-Type: application/json
X-Csrf-Token:

{
  "firstname": "testFirstname",
  "lastname": "testLastname",
  "email": "testMail",
  "password": "testPassword",
  "authority": "admin"
}

### Admin
GET localhost:8080/api/user/admin-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NjkzMjQyOTQsImlhdCI6MTY2OTIzNzg5NCwidXNlciI6eyJmaXJzdG5hbWUiOiJ0ZXN0Rmlyc3RuYW1lIiwicGFzc3dvcmQiOiJ0ZXN0UGFzc3dvcmQiLCJhdXRob3JpdHkiOiJBRE1JTiIsImlkIjowLCJlbWFpbCI6InRlc3RNYWlsIiwibGFzdG5hbWUiOiJ0ZXN0TGFzdG5hbWUifX0.B-578p7-xRjFHAfi4DOxRllwI9AjVD46h9yXZmhdNfQ

### User
GET localhost:8080/api/user/user-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NjkyMzkxMTMsImlhdCI6MTY2OTE1MjcxMywidXNlciI6eyJmaXJzdG5hbWUiOiJ0ZXN0Rmlyc3RuYW1lIiwicGFzc3dvcmQiOiJ0ZXN0UGFzc3dvcmQiLCJhdXRob3JpdHkiOiJBRE1JTiIsImlkIjowLCJlbWFpbCI6InRlc3RNYWlsIiwibGFzdG5hbWUiOiJ0ZXN0TGFzdG5hbWUifX0.NHN8VrpzFcHWRVY8yJbaAzqqzdTSdlRKNf1W3QVXBEo


### Editor
GET localhost:8080/api/user/editor-login
Authorization: Basic testMail testPassword


### Any-of-authority
GET localhost:8080/api/user/any-of-request-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwyIiwiZXhwIjoxNjY5MjM2MTE2LCJpYXQiOjE2NjkxNDk3MTYsInVzZXIiOiJBQUFBQUFBQUFBQUFBQUFBZHIrbnc2XC91NFdXTWpYdnh2VTIxcFA0Y0dQSWphRGZlQmtKb3U2SmJRTkxNeU02TTBFdHo0Q0JHZ1JhT081TGlKZ1hlS0NRWXREOFwvN3RJODJ4MWdCMlQzamV2N0QzSnVxOVVUazJYOFdHa2hrb1piNkhFN1BFYzBZalB3SWdpejQ5NFJseUJ2STdpb3JNQVRlVHh0aTZaTGR6OU5LSzBFQlRtdlRJb3BmeGpmdThIWjFwMG5jNnh0TDZcL1dLWU09In0.BY-8r9fSYjS-h_Z7_AuNxDEl1gt4N2FCYNXa2wycdJw
