### Register
POST localhost:8080/api/user/register
Content-Type: application/json

{
  "firstname": "testFirstname",
  "lastname": "testLastname",
  "email": "testMail",
  "password": "testPassword",
  "authority": "user"
}

### login
POST localhost:8080/api/user/login
Authorization: Basic testMail testPassword

### Admin
GET localhost:8080/api/user/admin-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NzE2MzM3NDcsImlhdCI6MTY3MTU0NzM0NywidXNlciI6eyJmaXJzdG5hbWUiOiJ0ZXN0Rmlyc3RuYW1lIiwicGFzc3dvcmQiOiJ0ZXN0UGFzc3dvcmQiLCJhdXRob3JpdHkiOiJFRElUT1IiLCJpZCI6MCwiZW1haWwiOiJ0ZXN0TWFpbCIsImxhc3RuYW1lIjoidGVzdExhc3RuYW1lIn19.x-C1IE2z4Q0CjxhABiQUkKecd6a9hsl03r9TRTgtQRk

### User
GET localhost:8080/api/user/user-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NzE0NDQ1MTMsImlhdCI6MTY3MTM1ODExMywidXNlciI6eyJmaXJzdG5hbWUiOiJ0ZXN0Rmlyc3RuYW1lIiwicGFzc3dvcmQiOiJ0ZXN0UGFzc3dvcmQiLCJhdXRob3JpdHkiOiJFRElUT1IiLCJpZCI6MCwiZW1haWwiOiJ0ZXN0TWFpbCIsImxhc3RuYW1lIjoidGVzdExhc3RuYW1lIn19.pW_kFT9audFgJQAl7qxPM-giDSltGZZWpvHeFkFhaik

### Editor
GET localhost:8080/api/user/editor-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NzEzOTUyMzcsImlhdCI6MTY3MTMwODgzNywidXNlciI6eyJmaXJzdG5hbWUiOiJ0ZXN0Rmlyc3RuYW1lIiwicGFzc3dvcmQiOiJ0ZXN0UGFzc3dvcmQiLCJhdXRob3JpdHkiOiJBRE1JTiIsImlkIjowLCJlbWFpbCI6InRlc3RNYWlsIiwibGFzdG5hbWUiOiJ0ZXN0TGFzdG5hbWUifX0.86Jx8czurXmDSdF3U2KtwpNFL7zT49CtDeC_SsiA0Zc

### Any-of-authority
GET localhost:8080/api/user/any-of-request-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NzExMjQ1NjQsImlhdCI6MTY3MTAzODE2NCwidXNlciI6eyJmaXJzdG5hbWUiOiJ0ZXN0Rmlyc3RuYW1lIiwicGFzc3dvcmQiOiJ0ZXN0UGFzc3dvcmQiLCJhdXRob3JpdHkiOiJBRE1JTiIsImlkIjowLCJlbWFpbCI6InRlc3RNYWlsIiwibGFzdG5hbWUiOiJ0ZXN0TGFzdG5hbWUifX0.IlBtGohHulYL2XpVlmBmgR6GUlzDQIm09p7clCSKd2M



