### Register
POST localhost:8080/api/user/register
Content-Type: application/json

{
  "firstname": "testFirstname",
  "lastname": "testLastname",
  "email": "testMail",
  "password": "testPassword",
  "authority": "admin"
}

### Admin
GET localhost:8080/api/user/admin-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqd3QtaW1wbGVtZW50YXRpb24iLCJzdWIiOiJ0ZXN0TWFpbCIsImV4cCI6MTY2OTM4MDI3MiwiaWF0IjoxNjY5MjkzODcyLCJ1c2VyIjp7ImZpcnN0bmFtZSI6InRlc3RGaXJzdG5hbWUiLCJwYXNzd29yZCI6InRlc3RQYXNzd29yZCIsImF1dGhvcml0eSI6IkFETUlOIiwiaWQiOjAsImVtYWlsIjoidGVzdE1haWwiLCJsYXN0bmFtZSI6InRlc3RMYXN0bmFtZSJ9fQ.gOGW69nF04QilvNqhch1mbVn0kWoEeewm148u5Y4fhI

### User
GET localhost:8080/api/user/user-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqd3QtaW1wbGVtZW50YXRpb24iLCJzdWIiOiJ0ZXN0TWFpbCIsImV4cCI6MTY2OTM4MDI3MiwiaWF0IjoxNjY5MjkzODcyLCJ1c2VyIjp7ImZpcnN0bmFtZSI6InRlc3RGaXJzdG5hbWUiLCJwYXNzd29yZCI6InRlc3RQYXNzd29yZCIsImF1dGhvcml0eSI6IkFETUlOIiwiaWQiOjAsImVtYWlsIjoidGVzdE1haWwiLCJsYXN0bmFtZSI6InRlc3RMYXN0bmFtZSJ9fQ.gOGW69nF04QilvNqhch1mbVn0kWoEeewm148u5Y4fhI


### Editor
GET localhost:8080/api/user/editor-login
Authorization: Basic testMail testPassword


### Any-of-authority
GET localhost:8080/api/user/any-of-request-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqd3QtaW1wbGVtZW50YXRpb24iLCJzdWIiOiJ0ZXN0TWFpbCIsImV4cCI6MTY2OTM4MDI3MiwiaWF0IjoxNjY5MjkzODcyLCJ1c2VyIjp7ImZpcnN0bmFtZSI6InRlc3RGaXJzdG5hbWUiLCJwYXNzd29yZCI6InRlc3RQYXNzd29yZCIsImF1dGhvcml0eSI6IkFETUlOIiwiaWQiOjAsImVtYWlsIjoidGVzdE1haWwiLCJsYXN0bmFtZSI6InRlc3RMYXN0bmFtZSJ9fQ.gOGW69nF04QilvNqhch1mbVn0kWoEeewm148u5Y4fhI

### me
GET localhost:8080/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqd3QtaW1wbGVtZW50YXRpb24iLCJzdWIiOiJ0ZXN0TWFpbCIsImV4cCI6MTY2OTM4MDI3MiwiaWF0IjoxNjY5MjkzODcyLCJ1c2VyIjp7ImZpcnN0bmFtZSI6InRlc3RGaXJzdG5hbWUiLCJwYXNzd29yZCI6InRlc3RQYXNzd29yZCIsImF1dGhvcml0eSI6IkFETUlOIiwiaWQiOjAsImVtYWlsIjoidGVzdE1haWwiLCJsYXN0bmFtZSI6InRlc3RMYXN0bmFtZSJ9fQ.gOGW69nF04QilvNqhch1mbVn0kWoEeewm148u5Y4fhI
