### Register
POST localhost:8080/api/user/register
Content-Type: application/json
X-Csrf-Token:

{
"firstname": "testFirstname",
"lastname": "testLastname",
"email": "testMail2",
"password": "testPassword",
"authority": "user"
}

### Admin
GET localhost:8080/api/user/admin-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwiLCJleHAiOjE2NjkyNDAyMjcsImlhdCI6MTY2OTE1MzgyNywidXNlciI6IkFBQUFBQUFBQUFBQUFBQUFkcitudzZcL3U0V1dNalh2eHZVMjFwUDRjR1BJamFEZmVCa0pvdTZKYlFOTE15TTZNMEV0ejRDQkdnUmFPTzVMaUpnWGVLQ1FZdEQ4XC83dEk4MngxZ0IyVDNqZXY3RDNKdXE5VVRrMlg4V0hrdm5OUksrbkVcL0pGb2lKQ3ZvZEJtbDVQb2doU0JyTzZXKzZzNGRPaWhzbDZGV2JDSkFjN1VjWmlpeFFKWXBmM2Y0VkhBZTJwb0tjTEhRTEVJWjB6dz0ifQ.duqp-yKDOTCxXJ_rt_oZXAP8uj3aSycBr6S8KXecSsQ

### User
GET localhost:8080/api/user/user-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwyIiwiZXhwIjoxNjY5MjQwMzA4LCJpYXQiOjE2NjkxNTM5MDgsInVzZXIiOiJBQUFBQUFBQUFBQUFBQUFBZHIrbnc2XC91NFdXTWpYdnh2VTIxcFA0Y0dQSWphRGZlQmtKb3U2SmJRTkxNeU02TTBFdHo0Q0JHZ1JhT081TGlKZ1hlS0NRWXREOFwvN3RJODJ4MWdCMlQzamV2N0QzSnVxOVVUazJYOFdHa2hrb1piNkhFN1BFYzBZalB3SWdpejQ5NFJseUJ2STdpb3JNQVRlVHh0aTZaTGR6OU5LSzBFQlRtdlRJb3BmeGpmdThIWjFwMG5jNnh0TDZcL1dLWU09In0.ZG7jo-pNF0LMurxxCWaNly1JyZpoxvhoMbNNOYUYaBs


### Editor
GET localhost:8080/api/user/editor-login
Authorization: Basic testMail testPassword


### Any-of-authority
GET localhost:8080/api/user/any-of-request-login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb2Z0cG9zLW1vYmlsZS1iYWNrZW5kIiwic3ViIjoidGVzdE1haWwyIiwiZXhwIjoxNjY5MjQwMzA4LCJpYXQiOjE2NjkxNTM5MDgsInVzZXIiOiJBQUFBQUFBQUFBQUFBQUFBZHIrbnc2XC91NFdXTWpYdnh2VTIxcFA0Y0dQSWphRGZlQmtKb3U2SmJRTkxNeU02TTBFdHo0Q0JHZ1JhT081TGlKZ1hlS0NRWXREOFwvN3RJODJ4MWdCMlQzamV2N0QzSnVxOVVUazJYOFdHa2hrb1piNkhFN1BFYzBZalB3SWdpejQ5NFJseUJ2STdpb3JNQVRlVHh0aTZaTGR6OU5LSzBFQlRtdlRJb3BmeGpmdThIWjFwMG5jNnh0TDZcL1dLWU09In0.ZG7jo-pNF0LMurxxCWaNly1JyZpoxvhoMbNNOYUYaBs
